### ISSUE TITLE
API responses serverseitig cachen?

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#7]

**Comment by reneweiser** [comment]
17c3e1a619bb45139708f75912a90562d88b419f adds client side caching using the browsers [session storage](https://developer.mozilla.org/de/docs/Web/API/Window/sessionStorage). It requests fresh data when the cache is 15 minutes old (can be adjusted if need be) or after reopening the browser window.

Server side caching requires a wordpress plugin like [WP REST Cache](https://wordpress.org/plugins/wp-rest-cache/).

See if client side caching is enough, otherwise we can also install the plugin.

**Comment by moritzebeling** [comment]
Also ich finde die Antworten dauern schon recht lang. Im normalen Betrieb der Website gibt es vermutlich wenige Inhalts-Änderungen und ein frische Antwort ist daher nicht besser als eine alte. Da das Plugin automatisch den Cache leert, wenn der Inhalt bearbeitet wird, denke ich es spricht nix dagegen...

**Comment by moritzebeling** [comment]
Oder zumindest mal ausprobieren

**Comment by reneweiser** [comment]
WP REST Cache hat bei mir die response Zeit von 2-5s auf 156ms reduziert.
